In [18]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df = pd.read_csv('train.txt',sep=';',header=None, names=['text','emotion'])

In [20]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [21]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [22]:
unique_emotions = df['emotion'].unique()
emotion_num = {}
i=0
for emo in unique_emotions:
    emotion_num[emo] = i
    i+=1

In [23]:
df['emotion'] = df['emotion'].map(emotion_num)
emotion_num

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [24]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

**makinn the text lowercasing**

In [25]:
df['text'] = df['text'].str.lower()

In [26]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

**removing punctuations**

In [27]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('', '', string.punctuation))

df['text'] = df['text'].apply(remove_punc)

**remove numbers**

In [28]:
def remove_numbers(txt):
    return txt.translate(str.maketrans('', '', string.digits))

df['text'] = df['text'].apply(remove_numbers)

**remove emojis**

In [29]:
def remove_emojis(txt):
    #return txt.encode('ascii', 'ignore').decode('ascii')
    #or
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

**remove stopwords**

In [30]:
def remove_stopwords(txt):
    stopwords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves',
                 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself',
                 'they', 'them', 'their', 'theirs', 'themselves',
                 'what', 'which', 'who', 'whom',
                 'this', 'that', "that'll", 
                 'these', 
                 'am','is','are','was','were','be','been','being',
                 'have','has','had','having',
                 'do','does','did','doing',
                 'a','an','the',
                 'and','but','if','or','because','as','until','while',
                 'of','at','by','for','with','about','against',
                 'between','into','through',
                 ]
    txt = [word for word in txt.split() if word not in stopwords]
    return " ".join(txt)

**remove stopwords 2nd method**

In [35]:
import nltk 
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))


from nltk.tokenize import word_tokenize
nltk.download('punkt')

def remove_stopwords_nltk(txt):
    word_tokens = word_tokenize(txt)
    cleaned_txt = []
    for i in word_tokens:
        if i not in stop_words:
            cleaned_txt.append(i)    
    return " ".join(cleaned_txt)

df['text'] = df['text'].apply(remove_stopwords_nltk)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vijay\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vijay\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

**remove links and urls**

In [47]:
import re

def remove_links(txt):
    return re.sub(r'http\S+|www\S+', '', txt)

df['text'] = df['text'].apply(remove_links)

In [36]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [37]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1