In [1]:
from pydoc import classify_class_attrs

import numpy as  np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

from pandas.core._numba import kernels

warnings.filterwarnings("ignore")

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

<ArrowStringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [5]:
from sklearn.model_selection import train_test_split
X = df.drop('species', axis=1)
y = df['species']

In [44]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier()

In [45]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [46]:
model_knn.score(X_test, y_test)   #overfit

0.98

In [20]:
from sklearn.svm import SVC

In [27]:
model_svm = SVC(gamma='auto')
model_svm.fit(X_train, y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [28]:
model_svm.score(X_test, y_test)#overfit

1.0

In [29]:
#now let's use the grid search CV

In [30]:
from sklearn.model_selection import GridSearchCV

In [38]:
classifier = GridSearchCV(model_svm,{ 'C' : [1,10,20,30], 'kernel':['rbf', 'linear']},cv = 5 , return_train_score= False )

In [39]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [40]:
classifier.cv_results_

{'mean_fit_time': array([0.00205617, 0.00177264, 0.00174251, 0.00165958, 0.0016705 ,
        0.00191913, 0.00191479, 0.0017199 ]),
 'std_fit_time': array([2.93233739e-04, 1.83459526e-04, 4.85579927e-05, 6.21292285e-05,
        3.90274829e-05, 1.00872486e-04, 1.61465919e-04, 3.89466510e-05]),
 'mean_score_time': array([0.00155854, 0.00132909, 0.00131764, 0.00126295, 0.00128884,
        0.00140867, 0.00139003, 0.00130529]),
 'std_score_time': array([2.49579775e-04, 3.57095322e-05, 2.48850527e-05, 1.18687441e-05,
        2.22782484e-05, 8.04110055e-05, 6.84779333e-05, 2.63899967e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [41]:
results = pd.DataFrame(classifier.cv_results_)

In [42]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002056,0.000293,0.001559,0.000250,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001773,0.000183,0.001329,0.000036,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001743,0.000049,0.001318,0.000025,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001660,0.000062,0.001263,0.000012,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001671,0.000039,0.001289,0.000022,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001919,0.000101,0.001409,0.000080,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001915,0.000161,0.001390,0.000068,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.001720,0.000039,0.001305,0.000026,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [43]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [49]:
param_grid = {
    'n_neighbors': list(range(1, 14)),
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

classifier2 = GridSearchCV(
    estimator=model_knn,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy'
)
classifier2.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [50]:
classifier2.cv_results_

{'mean_fit_time': array([0.00201755, 0.00157828, 0.00156765, 0.00158892, 0.00163612,
        0.00154409, 0.00161929, 0.00165868, 0.00168543, 0.00152588,
        0.00152168, 0.00149055, 0.00157433, 0.00155435, 0.0018518 ,
        0.00168376, 0.00158176, 0.00158896, 0.00169363, 0.00156107,
        0.0016078 , 0.00167646, 0.00159249, 0.00161338, 0.00158968,
        0.00161266, 0.00156627, 0.00160341, 0.00155311, 0.00158739,
        0.0016077 , 0.00163445, 0.00158811, 0.00157986, 0.00156994,
        0.00154858, 0.00161147, 0.00158772, 0.00160913, 0.00188451,
        0.00167623, 0.00158725, 0.00163198, 0.00165343, 0.001653  ,
        0.00160818, 0.00171804, 0.00163088, 0.00162339, 0.00175824,
        0.00169158, 0.00151224]),
 'std_fit_time': array([5.31319244e-04, 8.30967795e-05, 7.39969846e-05, 6.12424148e-05,
        8.47290925e-05, 2.07249250e-05, 6.46078982e-05, 1.74245524e-04,
        3.12346261e-04, 4.80885014e-05, 2.98899697e-05, 4.15249335e-05,
        9.20998843e-05, 3.39106660e-05, 1.33963748e-04, 1.29068060e-04,
        6.86962664e-05, 4.86342579e-05, 1.01868042e-04, 5.28204726e-05,
        2.76226625e-05, 7.79608484e-05, 3.60350103e-05, 6.42195391e-05,
        5.60928744e-05, 6.96786200e-05, 2.92292232e-05, 5.17108738e-05,
        8.99997767e-06, 4.78835686e-05, 5.19188741e-05, 1.00609205e-04,
        3.60984940e-05, 5.85453509e-05, 3.58641777e-05, 1.96399032e-05,
        7.41226453e-05, 1.63969594e-05, 6.21328881e-05, 1.23764221e-04,
        5.31562443e-05, 2.46523427e-05, 6.76480526e-05, 9.45070317e-05,
        5.12954456e-05, 3.00219644e-05, 9.11975218e-05, 5.13513107e-05,
        4.75583813e-05, 2.21677107e-04, 1.20169870e-04, 2.71861587e-05]),
 'mean_score_time': array([0.00262499, 0.00192103, 0.00226765, 0.00189209, 0.00247707,
        0.00188942, 0.00228114, 0.00201359, 0.00220103, 0.00183597,
        0.00227656, 0.00179486, 0.00231056, 0.00192184, 0.00259938,
        0.00198936, 0.00232038, 0.00194459, 0.00266709, 0.00190911,
        0.00233798, 0.00198388, 0.00229206, 0.00196781, 0.00237985,
        0.00196753, 0.00226011, 0.00189629, 0.00227442, 0.0019433 ,
        0.00233188, 0.00193319, 0.00229511, 0.00192575, 0.00235753,
        0.00191503, 0.00228782, 0.00193195, 0.00233989, 0.00244985,
        0.00240998, 0.00194693, 0.00238633, 0.00198178, 0.00243011,
        0.00203853, 0.00242081, 0.00198169, 0.00237699, 0.00206327,
        0.00253148, 0.00186248]),
 'std_score_time': array([4.03994552e-04, 9.30201139e-05, 6.73711002e-05, 5.91408807e-05,
        2.06886208e-04, 6.15185357e-05, 8.96241285e-05, 1.05377517e-04,
        1.05305619e-04, 1.31909052e-05, 7.75990909e-05, 2.32808875e-05,
        1.28261520e-04, 3.75780961e-05, 1.43772816e-04, 1.29199730e-04,
        1.98987980e-05, 2.01738751e-05, 4.16315231e-04, 5.19460631e-05,
        4.34357561e-05, 7.89460044e-05, 5.58566648e-05, 7.15950946e-05,
        5.10811235e-05, 1.60529196e-05, 3.10001368e-05, 2.23649336e-05,
        2.58640097e-05, 5.17712975e-05, 7.80098304e-05, 4.16938406e-05,
        6.38909480e-05, 4.52740246e-05, 9.05530461e-05, 4.25437629e-05,
        7.59850747e-05, 2.33062667e-05, 4.29443156e-05, 4.24266450e-04,
        9.18860873e-05, 6.04640046e-05, 9.50794641e-05, 4.89115933e-05,
        8.14686576e-05, 7.75130152e-05, 8.43351728e-05, 2.61154444e-05,
        4.67585944e-05, 1.38836361e-04, 3.07420559e-04, 4.76776119e-05]),
 'param_metric': masked_array(data=['euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                    10, 10, 11, 11, 12, 12, 13, 13, 1, 1, 2, 2, 3, 3, 4, 4,
                    5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12,
                    13, 13],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'metric': 'euclidean', 'n_neighbors': 1, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 1, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 2, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 2, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 4, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 4, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 6, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 6, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 8, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 8, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 9, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 9, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 10, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 10, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 12, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 12, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 13, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 13, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 1, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 1, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 4, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 4, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 6, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 6, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 8, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 8, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 10, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 10, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 12, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 12, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 13, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 13, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.96666667, 0.93333333, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 1.        , 1.        , 0.96666667, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.93333333,
        0.93333333, 0.96666667, 0.93333333, 0.93333333, 0.9       ,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 0.96666667,
        0.96666667, 0.93333333, 0.93333333, 0.93333333, 0.93333333,
        0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.9       ,
        0.9       , 0.93333333, 0.9       , 0.96666667, 0.9       ,
        0.93333333, 0.93333333, 0.93333333, 0.9       , 0.96666667,
        0.93333333, 0.96666667, 0.9       , 0.96666667, 0.93333333,
        0.96666667, 0.9       ]),
 'split3_test_score': array([0.93333333, 0.93333333, 0.9       , 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.93333333, 0.86666667, 0.93333333,
        0.93333333, 0.93333333, 0.9       , 0.93333333, 0.96666667,
        0.96666667, 0.9       , 0.93333333, 0.93333333, 0.96666667,
        0.9       , 0.93333333, 0.93333333, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.93333333,
        0.96666667, 0.96666667]),
 'split4_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ]),
 'mean_test_score': array([0.96      , 0.96      , 0.94666667, 0.96      , 0.96666667,
        0.96666667, 0.97333333, 0.96666667, 0.97333333, 0.96666667,
        0.98      , 0.98      , 0.98      , 0.98      , 0.96666667,
        0.98      , 0.97333333, 0.97333333, 0.98      , 0.98666667,
        0.98      , 0.98666667, 0.98      , 0.98666667, 0.97333333,
        0.98      , 0.96      , 0.96      , 0.93333333, 0.96      ,
        0.96      , 0.96      , 0.95333333, 0.96      , 0.96      ,
        0.96      , 0.95333333, 0.95333333, 0.97333333, 0.96      ,
        0.96      , 0.96666667, 0.96666667, 0.96      , 0.97333333,
        0.97333333, 0.98      , 0.96666667, 0.97333333, 0.96666667,
        0.97333333, 0.96666667]),
 'std_test_score': array([0.02494438, 0.02494438, 0.03399346, 0.02494438, 0.02108185,
        0.02108185, 0.01333333, 0.02108185, 0.02494438, 0.03651484,
        0.01632993, 0.01632993, 0.01632993, 0.01632993, 0.02981424,
        0.01632993, 0.02494438, 0.02494438, 0.02666667, 0.01632993,
        0.02666667, 0.01632993, 0.02666667, 0.01632993, 0.02494438,
        0.01632993, 0.02494438, 0.02494438, 0.03651484, 0.02494438,
        0.02494438, 0.02494438, 0.03399346, 0.02494438, 0.03265986,
        0.03265986, 0.03399346, 0.03399346, 0.02494438, 0.03265986,
        0.03887301, 0.02981424, 0.02981424, 0.03265986, 0.02494438,
        0.02494438, 0.01632993, 0.03651484, 0.02494438, 0.02981424,
        0.02494438, 0.03651484]),
 'rank_test_score': array([39, 39, 51, 39, 24, 24, 14, 24, 14, 24,  4,  4,  4,  4, 24,  4, 14,
        14,  4,  1,  4,  1,  4,  1, 14,  4, 39, 39, 52, 39, 39, 39, 48, 39,
        34, 34, 48, 48, 14, 34, 34, 24, 24, 34, 14, 14,  4, 24, 14, 24, 14,
        24], dtype=int32)}

In [51]:
results2 = pd.DataFrame(classifier2.cv_results_)

In [52]:
results2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002018,0.000531,0.002625,0.000404,euclidean,1,uniform,"{'metric': 'euclidean', 'n_neighbors': 1, 'wei...",0.966667,0.966667,0.933333,0.933333,1.000000,0.960000,0.024944,39
1,0.001578,0.000083,0.001921,0.000093,euclidean,1,distance,"{'metric': 'euclidean', 'n_neighbors': 1, 'wei...",0.966667,0.966667,0.933333,0.933333,1.000000,0.960000,0.024944,39
2,0.001568,0.000074,0.002268,0.000067,euclidean,2,uniform,"{'metric': 'euclidean', 'n_neighbors': 2, 'wei...",0.966667,0.933333,0.933333,0.900000,1.000000,0.946667,0.033993,51
3,0.001589,0.000061,0.001892,0.000059,euclidean,2,distance,"{'metric': 'euclidean', 'n_neighbors': 2, 'wei...",0.966667,0.966667,0.933333,0.933333,1.000000,0.960000,0.024944,39
4,0.001636,0.000085,0.002477,0.000207,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.000000,0.966667,0.021082,24
5,0.001544,0.000021,0.001889,0.000062,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.000000,0.966667,0.021082,24
6,0.001619,0.000065,0.002281,0.000090,euclidean,4,uniform,"{'metric': 'euclidean', 'n_neighbors': 4, 'wei...",0.966667,0.966667,0.966667,0.966667,1.000000,0.973333,0.013333,14
7,0.001659,0.000174,0.002014,0.000105,euclidean,4,distance,"{'metric': 'euclidean', 'n_neighbors': 4, 'wei...",0.966667,0.966667,0.933333,0.966667,1.000000,0.966667,0.021082,24
8,0.001685,0.000312,0.002201,0.000105,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.000000,0.973333,0.024944,14
9,0.001526,0.000048,0.001836,0.000013,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.000000,0.966667,0.036515,24
10,0.001522,0.000030,0.002277,0.000078,euclidean,6,uniform,"{'metric': 'euclidean', 'n_neighbors': 6, 'wei...",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,4
11,0.001491,0.000042,0.001795,0.000023,euclidean,6,distance,"{'metric': 'euclidean', 'n_neighbors': 6, 'wei...",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,4
12,0.001574,0.000092,0.002311,0.000128,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,4
13,0.001554,0.000034,0.001922,0.000038,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,4
14,0.001852,0.000134,0.002599,0.000144,euclidean,8,uniform,"{'metric': 'euclidean', 'n_neighbors': 8, 'wei...",0.966667,1.000000,0.933333,0.933333,1.000000,0.966667,0.029814,24
15,0.001684,0.000129,0.001989,0.000129,euclidean,8,distance,"{'metric': 'euclidean', 'n_neighbors': 8, 'wei...",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,4
16,0.001582,0.000069,0.002320,0.000020,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.000000,0.973333,0.024944,14
17,0.001589,0.000049,0.001945,0.000020,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.966667,1.000000,0.973333,0.024944,14
18,0.001694,0.000102,0.002667,0.000416,euclidean,10,uniform,"{'metric': 'euclidean', 'n_neighbors': 10, 'we...",0.966667,1.000000,1.000000,0.933333,1.000000,0.980000,0.026667,4
19,0.001561,0.000053,0.001909,0.000052,euclidean,10,distance,"{'metric': 'euclidean', 'n_neighbors': 10, 'we...",0.966667,1.000000,1.000000,0.966667,1.000000,0.986667,0.016330,1
20,0.001608,0.000028,0.002338,0.000043,euclidean,11,uniform,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.933333,1.000000,1.000000,0.966667,1.000000,0.980000,0.026667,4
21,0.001676,0.000078,0.001984,0.000079,euclidean,11,distance,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.966667,1.000000,1.000000,0.966667,1.000000,0.986667,0.016330,1
22,0.001592,0.000036,0.002292,0.000056,euclidean,12,uniform,"{'metric': 'euclidean', 'n_neighbors': 12, 'we...",0.933333,1.000000,1.000000,0.966667,1.000000,0.980000,0.026667,4
23,0.001613,0.000064,0.001968,0.000072,euclidean,12,distance,"{'metric': 'euclidean', 'n_neighbors': 12, 'we...",0.966667,1.000000,1.000000,0.966667,1.000000,0.986667,0.016330,1
24,0.001590,0.000056,0.002380,0.000051,euclidean,13,uniform,"{'metric': 'euclidean', 'n_neighbors': 13, 'we...",0.933333,1.000000,0.966667,0.966667,1.000000,0.973333,0.024944,14
25,0.001613,0.000070,0.001968,0.000016,euclidean,13,distance,"{'metric': 'euclidean', 'n_neighbors': 13, 'we...",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,4
26,0.001566,0.000029,0.002260,0.000031,manhattan,1,uniform,"{'metric': 'manhattan', 'n_neighbors': 1, 'wei...",0.966667,0.966667,0.933333,0.933333,1.000000,0.960000,0.024944,39
27,0.001603,0.000052,0.001896,0.000022,manhattan,1,distance,"{'metric': 'manhattan', 'n_neighbors': 1, 'wei...",0.966667,0.966667,0.933333,0.933333,1.000000,0.960000,0.024944,39
28,0.001553,0.000009,0.002274,0.000026,manhattan,2,uniform,"{'metric': 'manhattan', 'n_neighbors': 2, 'wei...",0.966667,0.933333,0.933333,0.866667,0.966667,0.933333,0.036515,52
29,0.001587,0.000048,0.001943,0.000052,manhattan,2,distance,"{'metric': 'manhattan', 'n_neighbors': 2, 'wei...",0.966667,0.966667,0.933333,0.933333,1.000000,0.960000,0.024944,39
30,0.001608,0.000052,0.002332,0.000078,manhattan,3,uniform,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.000000,0.960000,0.024944,39
31,0.001634,0.000101,0.001933,0.000042,manhattan,3,distance,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.000000,0.960000,0.024944,39
32,0.001588,0.000036,0.002295,0.000064,manhattan,4,uniform,"{'metric': 'manhattan', 'n_neighbors': 4, 'wei...",0.966667,0.966667,0.933333,0.900000,1.000000,0.953333,0.033993,48
33,0.001580,0.000059,0.001926,0.000045,manhattan,4,distance,"{'metric': 'manhattan', 'n_neighbors': 4, 'wei...",0.966667,0.966667,0.933333,0.933333,1.000000,0.960000,0.024944,39
34,0.001570,0.000036,0.002358,0.000091,manhattan,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.000000,0.960000,0.032660,34
35,0.001549,0.000020,0.001915,0.000043,manhattan,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.000000,0.960000,0.032660,34
36,0.001611,0.000074,0.002288,0.000076,manhattan,6,uniform,"{'metric': 'manhattan', 'n_neighbors': 6, 'wei...",0.966667,0.966667,0.933333,0.900000,1.000000,0.953333,0.033993,48
37,0.001588,0.000016,0.001932,0.000023,manhattan,6,distance,"{'metric': 'manhattan', 'n_neighbors': 6, 'wei...",0.966667,0.966667,0.900000,0.933333,1.000000,0.953333,0.033993,48
38,0.001609,0.000062,0.002340,0.000043,manhattan,7,uniform,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.933333,1.000000,0.973333,0.024944,14
39,0.001885,0.000124,0.002450,0.000424,manhattan,7,distance,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,0.966667,0.900000,0.966667,1.000000,0.960000,0.032660,34
40,0.001676,0.000053,0.002410,0.000092,manhattan,8,uniform,"{'metric': 'manhattan', 'n_neighbors': 8, 'wei...",0.966667,1.000000,0.933333,0.900000,1.000000,0.960000,0.038873,34
41,0.001587,0.000025,0.001947,0.000060,manhattan,8,distance,"{'metric': 'manhattan', 'n_neighbors': 8, 'wei...",0.966667,1.000000,0.933333,0.933333,1.000000,0.966667,0.029814,24
42,0.001632,0.000068,0.002386,0.000095,manhattan,9,uniform,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.933333,1.000000,0.966667,0.029814,24
43,0.001653,0.000095,0.001982,0.000049,manhattan,9,distance,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,0.966667,0.900000,0.966667,1.000000,0.960000,0.032660,34
44,0.001653,0.000051,0.002430,0.000081,manhattan,10,uniform,"{'metric': 'manhattan', 'n_neighbors': 10, 'we...",0.966667,1.000000,0.966667,0.933333,1.000000,0.973333,0.024944,14
45,0.001608,0.000030,0.002039,0.000078,manhattan,10,distance,"{'metric': 'manhattan', 'n_neighbors': 10, 'we...",0.966667,1.000000,0.933333,0.966667,1.000000,0.973333,0.024944,14
46,0.001718,0.000091,0.002421,0.000084,manhattan,11,uniform,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,4
47,0.001631,0.000051,0.001982,0.000026,manhattan,11,distance,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.900000,0.966667,1.000000,0.966667,0.036515,24
48,0.001623,0.000048,0.002377,0.000047,manhattan,12,uniform,"{'metric': 'manhattan', 'n_neighbors': 12, 'we...",0.966667,1.000000,0.966667,0.933333,1.000000,0.973333,0.024944,14
49,0.001758,0.000222,0.002063,0.000139,manhattan,12,distance,"{'metric': 'manhattan', 'n_neighbors': 12, 'we...",0.966667,1.000000,0.933333,0.933333,1.000000,0.966667,0.029814,24
50,0.001692,0.000120,0.002531,0.000307,manhattan,13,uniform,"{'metric': 'manhattan', 'n_neighbors': 13, 'we...",0.933333,1.000000,0.966667,0.966667,1.000000,0.973333,0.024944,14
51,0.001512,0.000027,0.001862,0.000048,manhattan,13,distance,"{'metric': 'manhattan', 'n_neighbors': 13, 'we...",0.966667,1.000000,0.900000,0.966667,1.000000,0.966667,0.036515,24

In [58]:
results2[['param_n_neighbors','param_metric','param_weights','mean_test_score']]

    param_n_neighbors param_metric param_weights  mean_test_score
0                   1    euclidean       uniform         0.960000
1                   1    euclidean      distance         0.960000
2                   2    euclidean       uniform         0.946667
3                   2    euclidean      distance         0.960000
4                   3    euclidean       uniform         0.966667
5                   3    euclidean      distance         0.966667
6                   4    euclidean       uniform         0.973333
7                   4    euclidean      distance         0.966667
8                   5    euclidean       uniform         0.973333
9                   5    euclidean      distance         0.966667
10                  6    euclidean       uniform         0.980000
11                  6    euclidean      distance         0.980000
12                  7    euclidean       uniform         0.980000
13                  7    euclidean      distance         0.980000
14                  8    euclidean       uniform         0.966667
15                  8    euclidean      distance         0.980000
16                  9    euclidean       uniform         0.973333
17                  9    euclidean      distance         0.973333
18                 10    euclidean       uniform         0.980000
19                 10    euclidean      distance         0.986667
20                 11    euclidean       uniform         0.980000
21                 11    euclidean      distance         0.986667
22                 12    euclidean       uniform         0.980000
23                 12    euclidean      distance         0.986667
24                 13    euclidean       uniform         0.973333
25                 13    euclidean      distance         0.980000
26                  1    manhattan       uniform         0.960000
27                  1    manhattan      distance         0.960000
28                  2    manhattan       uniform         0.933333
29                  2    manhattan      distance         0.960000
30                  3    manhattan       uniform         0.960000
31                  3    manhattan      distance         0.960000
32                  4    manhattan       uniform         0.953333
33                  4    manhattan      distance         0.960000
34                  5    manhattan       uniform         0.960000
35                  5    manhattan      distance         0.960000
36                  6    manhattan       uniform         0.953333
37                  6    manhattan      distance         0.953333
38                  7    manhattan       uniform         0.973333
39                  7    manhattan      distance         0.960000
40                  8    manhattan       uniform         0.960000
41                  8    manhattan      distance         0.966667
42                  9    manhattan       uniform         0.966667
43                  9    manhattan      distance         0.960000
44                 10    manhattan       uniform         0.973333
45                 10    manhattan      distance         0.973333
46                 11    manhattan       uniform         0.980000
47                 11    manhattan      distance         0.966667
48                 12    manhattan       uniform         0.973333
49                 12    manhattan      distance         0.966667
50                 13    manhattan       uniform         0.973333
51                 13    manhattan      distance         0.966667

In [66]:
from sklearn.model_selection import RandomizedSearchCV
classifier3 = RandomizedSearchCV((model_svm),
    {'C' : [1,10,20,30], 'kernel':['rbf', 'linear']},
    n_iter=4,cv=5,return_train_score= False)
classifier3.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10, gamma='auto', kernel='linear'),
                   n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [62]:

result3=pd.DataFrame(classifier3.cv_results_)

In [65]:
result3

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002186,0.000448,0.001628,0.000375,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,3
1,0.001698,0.000058,0.001313,0.000031,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,3
2,0.001730,0.000045,0.001341,0.000047,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,2
3,0.001776,0.000188,0.001340,0.000056,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [68]:
result3[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       30          rbf         0.960000
1       30       linear         0.960000
2       20          rbf         0.966667
3       10          rbf         0.980000